version: "2.1"

networks:
  dockernet:
    name: dockernet
    external: true

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - /home/${Z_USER}/containers/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      dockernet:
        ipv4_address: "${Z_IP_DASHBOARD}"
