version: "3"

networks:
  dockernet:
    name: dockernet
    external: true

volumes:
  portainer:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/home/${Z_USER}/containers/portainer/data"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
    restart: unless-stopped
    networks:
      dockernet:
        ipv4_address: "${Z_IP_PORTAINER}"

