pageInfo:
  title: Homelab

appConfig:
  statusCheck: true
  statusCheckInterval: 30
  iconSize: small
  theme: Nord

sections:
- name: Example Section
  icon: far fa-rocket
  items:
  - title: GitHub
    description: Dashy source code and docs
    icon: fab fa-github
    url: https://github.com/Lissy93/dashy
  - title: Issues
    description: View open issues, or raise a new one
    icon: fas fa-bug
    url: https://github.com/Lissy93/dashy/issues
- name: Network
  widgets:
  - type: pi-hole-stats
    options:
      hostname: process.env.pihole_ip
    icon: opnsense
    apiKey: process.env.pihole_key

